// Code generated by Kitva, DO NOT EDIT 

import type { Actions as Actions_ } from "./$types.js";
import {type RewriteActions, type FormResults, withValidation as wv, defineGenerated} from "kitva/generated";
import { actions_default_action, actions_another_action } from "$schemas/routes/form/basics/schemas";
import { localize } from "$lib/validation/localization";


export interface actions_default_action {
username: string
email: string
password: string
first_name: string
last_name?: string
accept_tos?: boolean
}

export interface actions_another_action {
foo: string
bar: string
}


export interface Schemas {
	actions: {
		default_action: actions_default_action
		another_action: actions_another_action
	}
}

type ActionsData = Schemas["actions"];

type Actions = RewriteActions<ActionsData, Actions_>;


export function withValidation<T extends Actions>(actions: T) {
	return wv(actions as FormResults<T, ActionsData>);
}

export const createDefaultActionForm = defineGenerated<ActionsData["default_action"]>("default_action", "kitva-Vm8", actions_default_action, localize)

export const createAnotherActionForm = defineGenerated<ActionsData["another_action"]>("another_action", "kitva-SWQ", actions_another_action, localize)