// Code generated by Kitva, DO NOT EDIT 
export interface actions_default_action {
username: string
email: string
password: string
first_name: string
last_name?: string
accept_tos?: boolean
}

export interface actions_another_action {
foo: string
bar: string
}

export interface Schemas {
	actions: {
		default_action: actions_default_action
		another_action: actions_another_action
	}
}