// Code generated by Kitva, DO NOT EDIT 

import type { Actions as Actions_ } from "./$types.js";
import {type RewriteActions, type FormResults, withValidation as wv, defineGenerated} from "kitva/generated";
import { actions_validated } from "$schemas/routes/form/server-only/schemas";
import { localize } from "$lib/validation/localization";


export interface actions_validated {
a: string
}


export interface Schemas {
	actions: {
		validated: actions_validated
	}
}

type ActionsData = Schemas["actions"];

type Actions = RewriteActions<ActionsData, Actions_>;


export function withValidation<T extends Actions>(actions: T) {
	return wv(actions as FormResults<T, ActionsData>);
}

export const createValidatedForm = defineGenerated<ActionsData["validated"]>("validated", "kitva-nbQ", actions_validated, localize)