// Code generated by Kitva, DO NOT EDIT 
export interface actions_default {
username: string
password: string
filled_by_server: string
}

export interface Schemas {
	actions: {
		default: actions_default
	}
}