// Code generated by Kitva, DO NOT EDIT 

import type { RewriteHandlers } from "kitva/generated"
import type { RequestHandler } from "./$types.js";

export interface POST_body {
username: string
password: string
}


export interface Schemas {
	POST: {
		body: POST_body
	}
}

type RequestHandlers = RewriteHandlers<Schemas, RequestHandler>;

export type POSTHandler = RequestHandlers["POST"];