// Code generated by Kitva, DO NOT EDIT 
export type POST_body = string

export interface actions_default {
a: string
}

export interface Schemas {
	POST: {
		body: POST_body
	}
	actions: {
		default: actions_default
	}
}