// Code generated by Kitva, DO NOT EDIT 

import type { RewriteHandlers } from "kitva/generated"
import type { RequestHandler } from "./$types.js";

import type { Actions as Actions_ } from "./$types.js";
import {type RewriteActions, type FormResults, withValidation as wv, defineGenerated} from "kitva/generated";
import { actions_default } from "$schemas/routes/form/with-endpoint/schemas";
import { localize } from "$lib/validation/localization";


export type POST_body = string

export interface actions_default {
a: string
}


export interface Schemas {
	POST: {
		body: POST_body
	}
	actions: {
		default: actions_default
	}
}

type RequestHandlers = RewriteHandlers<Schemas, RequestHandler>;

export type POSTHandler = RequestHandlers["POST"];

type ActionsData = Schemas["actions"];

type Actions = RewriteActions<ActionsData, Actions_>;


export function withValidation<T extends Actions>(actions: T) {
	return wv(actions as FormResults<T, ActionsData>);
}

export const createDefaultForm = defineGenerated<ActionsData["default"]>("default", "kitva-s1o", actions_default, localize)