// Code generated by Kitva, DO NOT EDIT 

import type { Actions as Actions_ } from "./$types.js";
import {type RewriteActions, type FormResults, withValidation as wv, defineGenerated} from "kitva/generated";
import { actions_default } from "$schemas/routes/form/group_binding/schemas";
import { localize } from "$lib/validation/localization";


export interface actions_default {
interests: string[]
}


export interface Schemas {
	actions: {
		default: actions_default
	}
}

type ActionsData = Schemas["actions"];

type Actions = RewriteActions<ActionsData, Actions_>;


export function withValidation<T extends Actions>(actions: T) {
	return wv(actions as FormResults<T, ActionsData>);
}

export const createDefaultForm = defineGenerated<ActionsData["default"]>("default", "kitva-yR0", actions_default, localize)